var svGlobal={version:"4.6",log:1,isMultitask:hi5.browser.isMultitask,util:{},logger:{debug:function(e){2<svGlobal.log&&console.log(e)},info:function(e){1<svGlobal.log&&console.log(e)},warn:function(e){0<svGlobal.log&&console.log(e)}}};function cancelDefault(e){e.preventDefault&&e.preventDefault();e.stopPropagation&&e.stopPropagation();return!1}
function LocalInterface(e){function v(a){var b=0,d=0,c=a.offsetParent;c&&c.offsetParent&&(c=c.offsetParent,b=c.scrollTop,d=c.scrollLeft);a.focus();b&&(c.scrollTop=b);d&&(c.scrollLeft=d)}function q(){var a=[];this.sent=!1;this.types=[];var b=this;this.datas=a;this.setData=function(d,c){if("text/plain"==d||"text/html"==d)2<c.length&&"`\t`"==c.substring(0,3)&&(c=c.substring(3)),c=c.replace(/\r?\n/g,"\r\n");b.types.push(d);a.push(c)};this.getData=function(d){return a[b.types.indexOf(d)]};this.equals=
function(a){if(!a||!hi5.Arrays.equals(b.types,a.types))return!1;for(var c,f,n=b.types,p=0,A=n.length;p<A;p++)if(c=n[p],f=b.getData(c),c=a.getData(c),f!=c)return!1;return!0}}function F(a){function b(){var b=h?a.value:a.innerText||a.textContent;B&&!h&&b.charAt(0)!=m.PLACE_HOLDER&&(b=m.PLACE_HOLDER+b);return b}function d(){var b=B?m.PLACE_HOLDER:"";k=b;m.setValue(b);if(B)if(h)a.setSelectionRange&&a.setSelectionRange(a.value.length,a.value.length);else if(a.focus(),"undefined"!=typeof window.getSelection&&
"undefined"!=typeof document.createRange){b=document.createRange();b.selectNodeContents(a);b.collapse(!1);var c=window.getSelection();c.removeAllRanges();c.addRange(b)}else"undefined"!=typeof document.body.createTextRange&&(b=document.body.createTextRange(),b.moveToElementText(a),b.collapse(!1),b.select())}function c(a){G=8==a.keyCode;if(m.onkeydown)m.onkeydown(a);return!0}function f(b){if(m.onkeyup)m.onkeyup(b);b=b.keyCode;1!=(h?a.value:a.innerText||a.textContent).length&&13!=b&&32!=b||setTimeout(d,
100);return!0}function n(a){if(m.onbackspace)for(var b=0;b<a;b++)m.onbackspace()}function p(c){if(!m.disableTextInput){c.stopPropagation();c=b();var f=c.length;1<f&&c.charAt(0)!=m.PLACE_HOLDER&&c.charAt(f-1)==m.PLACE_HOLDER&&(c=m.PLACE_HOLDER+c.substring(0,f-1),m.setValue(c));if(c!=k){var p=k.length,A=c.indexOf(k);if(c&&0===A){if(c=c.substring(p),0<c.length&&e&&m.ontextinput&&(m.ontextinput({data:c,target:a}),"."==c)){d();return}}else if(A=k.indexOf(c),0===A)G||n(p-f);else if(e&&(B&&(p--,c=c.substring(1)),
n(p),0<c.length&&m.ontextinput))m.ontextinput({data:c,target:a});""===b()&&setTimeout(d,100);k=b()}}}function A(a){if(!m.disableTextInput&&a.data){a.stopPropagation();if(m.ontextinput)m.ontextinput(a);g&&a.preventDefault()}}var m=this,B=hi5.browser.isAndroid&&hi5.browser.isChrome,e=hi5.browser.isFirefox||hi5.browser.isOpera||B,G=!1,g=!hi5.browser.isRIM,k="",h="INPUT"==a.nodeName||"TEXTAREA"==a.nodeName,l="DIV"==a.nodeName;this.PLACE_HOLDER="`";this.setValue=function(b){var c=m.disableTextInput;m.disableTextInput=
!0;h?a.value=b:l&&(a.innerHTML=b);m.disableTextInput=c};this.init=d;this.disableTextInput=!1;d();a.addEventListener("keydown",c,!1);a.addEventListener("keyup",f,!1);e?(a.addEventListener("input",p,!1),B?a.onclick=d:a.addEventListener("mouseup",d,!1)):(a.addEventListener("textInput",A,!1),a.addEventListener("textinput",A,!1));this.release=function(){a.removeEventListener("keydown",c,!1);a.removeEventListener("keyup",f,!1);a.removeEventListener("input",p,!1);a.removeEventListener("focus",d,!1)};this.select=
function(){Ta(a)}}function D(a,b,d){function c(a){var c=0,m=0,d=0,e=a.pageX-a.target.offsetLeft,G=a.pageY-a.target.offsetTop;a.wheelDelta?(d=(new Date).getTime(),100<d-n&&(f=0),m=a.wheelDelta,f+=m,c=f/120|0,f%=120,0!==c&&b(c,e,G),n=d):(c=-a.detail,32768==Math.abs(c)&&(m=window.innerHeight/40|0,c=0>c?-m:m),b(c,e,G))}var f=0,n=0;a.addEventListener("DOMMouseScroll",c,!0);a.addEventListener("mousewheel",c,!0)}function x(a){function b(a){if(!n&&p.onmousedown)p.onmousedown(a)}function d(a){if(!n&&p.onmousemove)p.onmousemove(a)}
function c(a){if(n)n=!1;else if(p.onmouseup)p.onmouseup(a)}function f(a){"touchstart"==a.type&&(n=!0);if(p.ontouch)p.ontouch(a)}var n=!1,p=this,A=navigator.pointerEnabled||navigator.msPointerEnabled||!1;"ontouchstart"in window||!A?(a.addEventListener("touchstart",f,!1),a.addEventListener("touchend",f,!1),a.addEventListener("touchmove",f,!1),a.addEventListener("touchcancel",f,!1),a.addEventListener("mousemove",d,!1),a.addEventListener("mousedown",b,!1),a.addEventListener("mouseup",c,!1)):navigator.pointerEnabled?
(a.addEventListener("pointerdown",f,!1),a.addEventListener("pointerup",f,!1),a.addEventListener("pointermove",f,!1),a.addEventListener("pointercancel",f,!1)):navigator.msPointerEnabled&&(a.addEventListener("MSPointerDown",f,!1),a.addEventListener("MSPointerUp",f,!1),a.addEventListener("MSPointerMove",f,!1),a.addEventListener("MSPointerCancel",f,!1))}function r(){return k.railWin?!0:!ca&&O<=window.innerWidth&&L<=window.innerHeight}function y(a){function b(a,b){for(var d,m=a.length,f=Array(m),e=h.getElement().getBoundingClientRect(),
G=0;G<m;G++){d=a[G];var k=G,g;g=d.identifier;if(!(256>g)){var l=c.indexOf(g);-1!=l?g=l:(c.push(g),g=c.length-1)}f[k]={contactId:g,contactFlags:b,x:d.pageX-e.left,y:d.pageY-e.top}}return f}var d,c=[],f=!1;this.handle=function(n){var p=n.type,A=n.touches,m=n.changedTouches;cancelDefault(n);switch(p){case "touchstart":f=!1;d=n=b(A,25);break;case "touchmove":n=b(m,26);p=!1;if(0<d.length&&1==n.length){a:{A=d.length;for(m=0;m<A;m++)if(d[m].contactId==n[0].contactId){A=m;break a}A=-1}-1!=A&&d[A].x==n[0].x&&
d[A].y==n[0].y&&(p=!0)}if(p)break;else 0<d.length&&(a.redirectTouches(d),d.length=0);a.redirectTouches(n);f=!0;break;case "touchend":if(f)n=b(m,4);else{a.redirectTouches(d);n=d.length;for(p=0;p<n;p++)d[p].contactFlags=4;n=d}a.redirectTouches(n);c.length=d.length=0;break;case "touchcancel":a.redirectTouches(b(m,34)),c.length=d.length=0}}}function H(a){function b(a){var b=a[1].screenX-a[0].screenX;a=a[1].screenY-a[0].screenY;return Math.sqrt(b*b+a*a)}function d(a,m){var d=[],f=c(a,u[0].identifier)||
c(m,u[0].identifier);f&&d.push(f);(f=c(a,u[1].identifier)||c(m,u[1].identifier))&&d.push(f);f="";if(2!=d.length)return f;var n=b(d)-b(u);60>Math.abs(n)?80<d[0].screenX-u[0].screenX?f="RIGHT":80<u[0].screenX-d[0].screenX?f="LEFT":80<d[0].screenY-u[0].screenY?f="DOWN":80<u[0].screenY-d[0].screenY&&(f="UP"):f=0>n?"CLOSE":"OPEN";return f}function c(a,b){for(var c=0,m=a.length;c<m;c++)if(a[c].identifier==b)return a[c];return null}function f(a){this.identifier=a.pointerId;this.pageX=a.pageX;this.pageY=
a.pageY;this.screenX=a.screenX;this.screenY=a.screenY}var n=0,p=0,A=0,m=0,B=!1,e=0,G=0,g=0,k=0,h=!1,l=!1,t=3,q=!1;W&&(t*=3);this.delay=!1;var u=[],x=this;this.handlePointer=function(a){if(a.pointerType==a.MSPOINTER_TYPE_MOUSE||"mouse"==a.pointerType)switch(a.type){case "MSPointerDown":case "pointerdown":ya(a);break;case "pointermove":case "MSPointerMove":za(a);break;case "pointerup":case "MSPointerUp":Aa(a)}else a.touches=a.changedTouches=[new f(a)],x.handle(a)};this.handle=function(b){var f=b.type,
z=0,z=b.touches,x=b.changedTouches,v,y;switch(f){case "touchstart":case "MSPointerDown":case "pointerdown":moveSpace=moveCount=0;q=!1;p="touchstart"==f?z.length:p+1;l=!1;m=(new Date).getTime();B=1==p&&200>m-A;f=z[0];n=f.identifier;e=f.pageX;G=f.pageY;h=!0;2!=z.length?q=!1:(v=z[1].screenX-z[0].screenX,q=100<Math.abs(z[1].screenY-z[0].screenY)||350<Math.abs(v));(B||2<p)&&cancelDefault(b);if(3==p){for(var f=y=v=0,x=9999,H=0,C=z.length;H<C;H++)z[H].screenY>f&&(f=z[H].screenY,v=H),z[H].screenY<x&&(x=z[H].screenY,
y=H);u=[{screenX:z[y].screenX,screenY:z[y].screenY,identifier:z[y].identifier},{screenX:z[v].screenX,screenY:z[v].screenY,identifier:z[v].identifier}]}break;case "pointermove":case "MSPointerMove":if(1<p)break;case "touchmove":if(q)return;1==p&&r()&&(w.disableScoll||window.scrollTo(0,0),cancelDefault(b));f=x[z.length-1];if(f.identifier!=n&&(f=c(x,n),!f)){cancelDefault(b);return}v=f.pageX;y=f.pageY;if(h){if(0===v-e&&0===y-G)return;if(Math.abs(v-e)<t&&Math.abs(y-G)<t){cancelDefault(b);return}h=!1;z=
(new Date).getTime()-m;if((l=180>z)&&!r()&&1==p){q=!0;return}a.touchstart({x:e,y:G,flick:l,pointes:p,screenX:f.screenX,screenY:f.screenY,moved:!0,target:b.target})}cancelDefault(b);a.touchmove({x:v,y:y,flick:l,pointes:p,moved:!0,screenX:f.screenX,screenY:f.screenY,target:b.target});break;case "MSPointerUp":case "touchend":case "pointerup":if(q)return;if(3==x.length+z.length){a.touchend({x:v,y:y,flick:l,pointes:p,moved:!h,target:b.target,gesture:d(z,x)});p=0;break}else{if(2<p){p=0;break}if(f=c(x,n))x=
(new Date).getTime(),v=f.pageX,y=f.pageY,l?a.touchend({x:v,y:y,flick:!0,pointes:p,moved:!h,screenX:f.screenX,screenY:f.screenY,target:b.target}):(z=x-m,h?(A=x,B?cancelDefault(b):(g=v,k=y),500>z?(A=x,a.touchstart({x:g,y:k,flick:!1,pointes:p,screenX:f.screenX,screenY:f.screenY,moved:!1,target:b.target}),a.touchend({x:g,y:k,flick:!1,pointes:p,moved:!1,screenX:f.screenX,screenY:f.screenY,target:b.target})):a.longpress({x:v,y:y,flick:!1,pointes:p,moved:!1,screenX:f.screenX,screenY:f.screenY,target:b.target})):
a.touchend({x:v,y:y,flick:!1,pointes:p,moved:!0,screenX:f.screenX,screenY:f.screenY,target:b.target}))}p=0;break;case "MSPointerCancel":case "touchcancel":p=0}B&&cancelDefault(b)}}function Ua(){l(!0,14);l(!1,14)}function Ta(a){try{a.select?a.select():hi5.browser.selectEditable(a)}catch(b){console.log(b)}}function Va(){function a(){f.focus()}function b(b,c){var d=document.createElement("a");d.href="#";d.accessKey=b;d.onfocus=a;d.style.position="absolute";d.style.width=1;d.style.height=1;d.style.left=
0;d.style.top=c+"px";return d}var d=hi5.browser.isIE,c=document.createElement(d?"textarea":"div"),f=this;this.setFontSize=function(a){c.style.fontSize=w.inputFontSize||a};d?(c.style.opacity=0,c.readOnly=C&&hi5.browser.isMetro?!0:!1):c.contentEditable=!C||hi5.browser.isChrome&&(hi5.browser.isWindows||hi5.browser.isCrOS)?!0:!1;c.accessKey="f";c.id="wsinput";c.tabIndex=1;c.style.opacity=0;c.style.resize="none";c.style.position="absolute";c.style.margin="0";c.style.border="none";c.style.outline="none";
var n=hi5.tool.getPos(e,!0);c.style.left=n.x+"px";c.style.top=n.y+"px";c.style.paddingRight=0;c.style.paddingBottom=0;c.style.width="10px";c.style.height="10px";c.style.zIndex=88;c.style.cursor="default";c.style.fontWeight="normal";c.style.fonStyle="normal";c.style.overflow="hidden";I=new F(c);I.onbackspace=Ua;n=e.parentNode;n.appendChild(c);W&&(n.appendChild(b("E"),60),n.appendChild(b("V"),61),n.appendChild(b("A"),62),n.appendChild(b("T"),63),n.appendChild(b("H"),64));var p=c.style.opacity;this.resetCSS=
function(){_fontSize=c.style.fontSize;p=c.style.opacity;c.style.opacity=0};this.restoreCSS=function(){c.style.opacity=p};this.getValue=function(){return d?c.value:c.innerHTML};this.setValue=function(a){I&&(I.disableTextInput=!0);d?c.value=a:c.innerHTML=a;I&&(I.disableTextInput=!1)};this.focus=function(){f.setValue(" ");v(c)};this.setContentEditable=function(a){d?c.readOnly==a&&(c.readOnly=!a):c.contentEditable!=a&&(c.contentEditable=a,"true"==a&&W&&hi5.browser.selectEditable(c))};this.isIMEMode=!1;
this.setIMEStatus=function(a){a?f.isIMEMode||(d&&(c.style.background="transparent",c.style.opacity=1),f.isIMEMode=!0):f.isIMEMode&&(d&&(c.style.background="",c.style.opacity=0),f.isIMEMode=!1)};this.adjust=function(a){var b=hi5.tool.getPos(e,!0),d=k.railWin?Math.min(window.innerWidth-b.x,O):O,n=k.railWin?Math.min(window.innerHeight-b.y,L):L,p=Math.min(window.innerWidth-b.x,O),g=Math.min(window.innerHeight-b.y,L),p=Math.round(.7*p);a=Math.round(g*(a?.99:.7));d-=p;n-=a;w.disableAdjust&&(a=p=0,d=e.offsetWidth+
"px",n=e.offsetHeight+"px");c.style.width=d+"px";c.style.height=n+"px";c.style.paddingLeft=p+"px";c.style.paddingTop=a+"px";c.style.left=b.x+"px";c.style.top=b.y+"px";c.style.textIndent=-(p+(W?48:0))+"px";hi5.browser.isFirefox&&(c.style.fontSize=0);C&&hi5.browser.isChrome&&f.setFontSize("2em");w.disableScoll||window.scrollTo(0,0)};this.remove=function(){c.parentNode&&c.parentNode.removeChild(c)};this.hide=function(){c.style.visibility="hidden"};this.getElement=function(){return c};this.select=function(){Ta(c)}}
function Ba(){g||(g=hi5.$("svImgCursor"),g||(g=document.createElement("canvas"),g.id="svImgCursor",g.style.position="absolute",g.style.left=90,g.style.top=90,g.scrX=0,g.scrY=0,g.hotX=10,g.hotY=10,g.width=g.height=32,document.body.appendChild(g),"ontouchstart"in window?(g.addEventListener("touchstart",P,!1),g.addEventListener("touchend",P,!1),g.addEventListener("touchmove",P,!1),g.addEventListener("touchcancel",P,!1)):navigator.pointerEnabled?(g.addEventListener("pointerdown",P,!1),g.addEventListener("pointerup",
P,!1),g.addEventListener("pointermove",P,!1),g.addEventListener("pointercancel",P,!1)):navigator.msPointerEnabled&&(g.addEventListener("MSPointerDown",P,!1),g.addEventListener("MSPointerUp",P,!1),g.addEventListener("MSPointerMove",P,!1),g.addEventListener("MSPointerCancel",P,!1)),g.setCursor=function(a){var b=a.width,d=a.height,c=a.rawData,f=b*d,n=0,p=0;if(!(1>f)){g.hotX=a.hotX;g.hotY=a.hotY;g.width=b;g.height=d;a=g.getContext("2d");var e=a.createImageData(b,d),m=e.data;if(c){for(b=0;b<f;b++)n=c[b],
m[p++]=n&255,m[p++]=n>>8&255,m[p++]=n>>16&255,m[p++]=n>>24&255;a.putImageData(e,0,0)}else a.fillStyle="rgba(0,0,0,0)",a.fillRect(0,0,b,d)}},Ca?g.setCursor(Ca):g.setCursor({rawData:[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,
-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-1,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-1,-1,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,
-1,-1,-1,-1,-1,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-1,-1,-1,-1,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-1,-1,-1,-1,-1,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-1,-1,-1,-1,-16777216,-16777216,-16777216,-16777216,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-1,-16777216,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-16777216,-16777216,
-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-16777216,0,0,-16777216,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-16777216,0,0,0,-16777216,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,0,0,0,0,0,-16777216,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],width:32,height:32})))}function Wa(a){if(!1!==w.disableScrollbars){var b=document.body;a?(Da=a,b.style.overflow=a):(Da=O<=window.innerWidth&&L<=window.innerHeight?"hidden":"visible",b.style.overflow=Da)}}function la(a){var b=document.body,d=window.innerWidth,c=window.innerHeight;
Math.max(O,L)<Math.max(d,c)&&Math.min(O,L)<Math.min(d,c)?1!=M&&(hi5.tool.scale(b,1),M=1):(b.style.overflow="hidden",M=a?Math.min(window.innerWidth/O,window.innerHeight/L):1,hi5.tool.scale(b,M))}function Xa(){var a=chrome.app.window.current();a&&a.fullscreen()}function Ea(a){a||(a="div");var b=document.createElement(a),d=document.body;b.id="_tmpEditable";"div"==a&&(b.contentEditable=!0);b.style.position="absolute";b.style.zIndex=9999;b.style.left=d.scrollLeft+50+"px";b.style.top=d.scrollTop+50+"px";
b.tabIndex=2;b.style.outline="none";b.style.opacity=0;d.appendChild(b);return b}function Ya(a){Fa.clearPDF();k.focused=!0;t.onfocus(a);sa=!0;da.sendMissKey();t.send("891");S&&u&&u.startPasteCmd()}function Za(a){var b=__svi18n.remoteApp.close;if(!$a&&k.railWin&&k.railWin.isRunning()&&b&&(a||(a=window.event),2!=t.getAppMode()))return k.showMessage(b),a&&(a.returnValue=b),b}function Ga(a){k.focused=!1;if(k.onunload)k.onunload()}function Ha(){h&&(h.getElement().oncontextmenu=function(){return!1},W||(h.getElement().onselectstart=
function(){return!1}))}function Ia(){h&&(h.getElement().oncontextmenu=null,h.getElement().onselectstart=null)}function zb(a){h&&h.adjust();if(ea)la(!0);else if(!(ca&&2500>(new Date).getTime()-ca)){var b=hi5.browser.isWindows&&!hi5.browser.isMetro;if(!C||b)t.onresize(a)}}function Ab(){window.svSurface||(window.svSurface=k);window.addEventListener("resize",zb,!1);if(!T){var a=!hi5.browser.isChromeApp;a&&window.addEventListener("beforeunload",Za,!1);a?window.addEventListener("unload",Ga,!1):chrome.runtime.onSuspend.addListener(Ga);
Ha();window.addEventListener("focus",Ya,!1);window.addEventListener("blur",function(a){k.focused=!1},!1);hi5.browser.isChromeApp&&chrome.app.window.current().onMaximized.addListener(Xa);(a=hi5.$("saveSession"))&&a.addEventListener("change",function(a){t.saveSession({save:a.target.checked})})}}function Bb(){try{var a=window.parent;if(a!=window)return a}catch(b){}return null}function ab(){if(!N){var a=hi5.$("touchGesture");a&&(a.style.display="block");if(a=hi5.$("extKBD"))a.onchange=function(a){k.setExtKeyboard(a.target.checked)};
N=hi5.$("svTouchInput");(a=Bb())&&!N&&(N=a.document.getElementById("svTouchInput"));N&&(hi5.browser.isWindows&&(a=document.createElement("div"),a.contentEditable=!0,a.id="svTouchInput",N.parentNode.replaceChild(a,N),N=a),hi5.browser.isChrome&&(N.style.fontSize="2em"),E=new F(N),E.onkeydown=E.onkeyup=bb,E.ontextinput=cb,E.onbackspace=Ua)}}function ma(a,b){function d(a,c){var d=document.createElement("span");d.data_path=a;d.className="path";d.innerHTML=c;d.onclick=function(){ma(this.data_path,b)};return d}
function c(a){for(var b=f;b.hasChildNodes();)b.removeChild(b.firstChild);var c=d("/","&nbsp&nbsp&nbsp/");b.appendChild(c);if("/"!=a&&""!==a){a=a.split("/");for(var m="/",B=0,e=a.length;B<e;B++)c=a[B],""!==c&&(m=m+a[B]+"/",c=d(m,c+"/"),b.appendChild(c))}}var f=hi5.$("parentPath");f.currentDir||(f.currentDir="/");"."==a?a=f.currentDir:f.currentDir=a;f.currentDir=a;t.getShareFiles(a,function(a){function d(b){b||(b=m.getValue("Name"));var c=a.parent;if(""===c||"/"!=c.charAt(c.length-1))c+="/";return c+
b}a.error&&k.showMessage(__svi18n.file[a.error]);var f=new hi5.DataTable(a),m=new hi5.DataGrid(hi5.$("filelist"));m.dataTable=f;var B=hi5.tool.bytesToSize;m.beforeDisplayValue=function(a,b){var c=f.cols[a].name;return"Date Modified"==c?(new Date(b)).toLocaleString():"Size"==c?B(b):"Type"==c&&"folder"==b?__svi18n.file.folder:"Name"==c?decodeURIComponent(b):b};m.onrowclick=function(c){var f=m.getValue("Name"),B=m.getValue("Type"),e=d(f);c=c.target.name;"delete"==c?(J.removeFile(e),ma(a.parent,b)):"folder"==
B?ma(("/"==a.parent?"":a.parent)+"/"+f,b):("view"==c&&(e+="&action=view"),t.getFile(e))};m.beforeAppendRow=function(a){var b;if("folder"==f.getValue(f.getColNo("Type"))){if(b=a.querySelector('img[name="download"]'))b.style.visibility="hidden"}else{a.draggable=!0;b=m.getValue("Name");var c=d(b),c="application/octet-stream:"+b+":"+t.getFileLink(c);a.addEventListener("dragstart",function(a){a.dataTransfer.setData("DownloadURL",c)},!1);if(10<b.length&&".uploading"==b.substring(b.length-10)){if(b=a.querySelector('img[name="download"]'))b.style.visibility=
"hidden";if(b=a.querySelector('img[name="view"]'))b.style.visibility="hidden"}}};m.open();c(a.parent);var e=document.getElementById("__diskSpace");e&&(e.innerHTML=hi5.tool.bytesToSize(a.freeSpace)+"/"+hi5.tool.bytesToSize(a.totalSpace));b.resize()})}function db(a){a&&cancelDefault(a);a=hi5.$("filecontainer");U=new hi5.Lightbox(a);ma(".",U);U.show()}function Ja(){var a=hi5.$("svToolbar");if(a){for(var b=a.childNodes,d=!1,c=0,f=b.length;c<f;c++)if(1==b[c].nodeType&&-1==["svTouchInput","svCloud","svInfo"].indexOf(b[c].id)){d=
!0;break}b=hi5.$("appinfo");if(k.showToolbar&&(C||J||b||d)){if(d=null===k.toolbar)k.toolbar=new hi5.Toolbar(a);C?k.toolbar.activeObj=N:(a=hi5.$("svTouchInput"))&&a.parentNode.removeChild(a);if(a=k.toolbar.getButton("svCloud"))J?(a.style.display="",a.onclick=db):a.style.display="none";new hi5.Fadable(k.toolbar,w.toolbar.fadeDelay||5E3,h.getElement());a=w.toolbar.fadable;k.toolbar.setFadable(a);a&&(k.toolbar.style.display="none");if(a=k.toolbar.getButton("svInfo"))b?(a.style.display="",d&&(a.onclick=
function(a){cancelDefault(a);a=t.getAppInfo();var b=hi5.$("numericId");b&&(b.innerHTML=a.numericId);if(b=hi5.$("connectingTo"))b.innerHTML=a.server;if(b=hi5.$("joinLink"))b.href=b.innerHTML=a.joinLink;a=new hi5.Lightbox(hi5.$("appinfo"));a.show();Ia();a.onclose=Ha})):a.style.display="none";if(k.onloadtoolbar)k.onloadtoolbar(k.toolbar)}}}function eb(a){J.addFiles(a.target.files);a=hi5.$("uploadfile");var b=a.cloneNode(!0);a.parentNode.replaceChild(b,a);b.addEventListener("change",eb,!1)}function Cb(){var a=
h.getElement();J&&!T&&(svGlobal.util.initMapDisk(a,J),svGlobal.util.initMapDisk(hi5.$("filecontainer"),J),hi5.$("uploadfile").addEventListener("change",eb,!1))}function fb(a){a.target!=h.getElement()&&fa(gb,hb,a.button)}function Ka(a,b,d){if(g){a=g.scrX+a;b=g.scrY+b;0>a?a=0:a>O&&(a=O-1);0>b?b=0:b>L&&(b=L-1);var c=e.getBoundingClientRect();g.scrX=a;g.scrY=b;g.style.left=(c.left+a-g.hotX)/M+"px";g.style.top=(c.top+b-g.hotY)/V+"px";K&&!d&&t.sendInput("82"+a+"\t"+b)}}function na(a,b,d){g||Ba();a=a*M|
0;b=b*V|0;Ka(a-g.scrX,b-g.scrY,d)}function La(a,b,d,c){var f;switch(a){case "touchstart":Ma=!1;0===g.scrX&&0===g.scrY&&na(b-50,d-50);c&&t.sendInput("80"+g.scrX+"\t"+g.scrY+"\t0");break;case "touchmove":c=b-ta;a=d-ga;if(0===c&&0===a)return;f=5>Math.abs(ib)&&5>Math.abs(jb)&&(7<Math.abs(c)||7<Math.abs(a));f||(Ka(c,a),Ma=!0);ib=c;jb=a;break;case "touchend":(a=!Ma&&!c)&&t.sendInput("80"+g.scrX+"\t"+g.scrY+"\t0"),(a||c)&&t.sendInput("81"+g.scrX+"\t"+g.scrY+"\t0")}ta=b;ga=d}function P(a){K&&("ontouchstart"in
window?oa.handle(a):oa.handlePointer(a))}function bb(a){if(!K)return!1;da.check(a);var b=ha.getKeyCode(a),d="keydown"==a.type;d&&h&&h.setIMEStatus(229==b);if(18==b&&(kb&&d&&(Na=2==(a.location||a.keyLocation)),Na))return!0;if(lb(a,b,d))return cancelDefault(a);17!=b||d||(pa=!1);var c=mb(b);if(0<c)return l(d,c),c=a.target==h.getElement(),d&&ia&&h&&17==b&&(hi5.browser.isFirefox||hi5.browser.isSafari||W&&!c)&&(c?(h.setValue("`\t`"),h.select()):(E.setValue("`\t`"),E.select())),cancelDefault(a);if(a.ctrlKey||
a.altKey&&!Na||a.metaKey)return(86!=b||!a.ctrlKey&&!a.metaKey||a.ctrlKey&&a.altKey||!S)&&R(d,b),d&&(ua=b),17==b||(a.ctrlKey||a.metaKey)&&(86==b||67==b||88==b)?(!d||67!=b&&88!=b||(pa=!0),!0):a.altKey&&!a.ctrlKey||a.ctrlKey&&!a.altKey?cancelDefault(a):!0;if(!(b!=ua||d||a.ctrlKey&&a.altKey))return R(!1,b),ua=0,!0;ua=0;return!0}function lb(a,b,d){if(!a.altKey)return!1;switch(b){case 8:case 35:if(!a.ctrlKey&&!a.metaKey)return!1;l(d,211);break;case 33:l(d,15);break;case 34:d?(l(!0,42),l(!0,15)):(l(!1,15),
l(!1,42));break;case 45:l(d,1);break;case 36:d?(l(!1,56),l(!0,29),l(!0,1)):(l(!1,1),l(!1,29));break;default:return!1}return!0}function Db(a){if(!K)return!1;da.check(a);var b=ha.getKeyCode(a),d="keydown"==a.type,c=da.preKeyCode;d?h&&h.setIMEStatus(229==b):h&&h.isIMEMode&&W&&h&&h.setIMEStatus(!1);if(lb(a,b,d))return cancelDefault(a);da.preKeyCode=b;if(229==b||229==c&&!d)return!0;44==b?(l(!0,170),l(!0,183),c=!0):19==b?(d?(l(!0,225),l(!0,29),l(!0,69),l(!0,225),l(!0,157),l(!0,197)):l(!1,29),c=!0):c=!1;
if(c)return cancelDefault(a);(c=ha.getScancode(a))||(c=mb(b)||0);var f=86==b&&(nb&&!d||(a.ctrlKey||a.metaKey)&&!(a.ctrlKey&&a.altKey))&&S;0<c&&!f?l(d,c):f||R(d,b);17!=b&&(nb=f);return 17==b||(a.ctrlKey||a.metaKey)&&(86==b||67==b||88==b)?(d&&(17==b&&ia&&h&&(h.setValue("`\t`"),h.select()),67==b||88==b)&&(pa=!0),17!=b||d||(pa=!1),!0):144==b||16==b?!1:cancelDefault(a)}function cb(a){if(K&&(a=a.data,!(!C&&va&&1==a.length&&128>a.charCodeAt(0))&&"`\t`"!=a)){var b=aa||ba;b&&(a=a.toLowerCase());W&&(a=a.replace(/\u00a0/g,
" "));t.sendInput("86"+a+"\t"+(b||va?1:0));X&&X.resetModifier()}}function ob(){l(!0,29);R(!0,86);R(!1,86);l(!1,29)}function Eb(a){var b=0===a.types.length||a.equals(u.clipData);b||a.types.join(",");var d=0;b||(b=(b=a.getData("text/html"))?b.replace(/(<([^>]+)>)|\r?\n/gi,""):a.getData("text/plain"))&&(d=b.hashCode());t.send("880"+a.types.join(",")+"\t"+d);u.clipData=a;a=!0;k.onclipdata&&(a=!k.onclipdata(u.clipData));a&&setTimeout(ob,500)}function ja(a,b){if(k.onscancode){var d=k.onscancode(a,b);if(d){for(var c=
0,f=d.length;c<f;c++)t.sendInput("84"+(d[c].down?0:49152)+"\t"+d[c].key);return}}t.sendInput("84"+(a?0:49152)+"\t"+b)}function l(a,b){if(K)if(184==b)ja(a,29),ja(a,56);else switch(!a&&(hi5.browser.isCrOS&&61<b&&69>b||58==b&&pb||95==b)&&ja(!0,b),95!=b&&ja(a,b),b){case 221:a&&ja(!1,221);break;case 58:pb&&a&&ja(!1,58)}}function R(a,b){K&&(111==b?a&&t.sendInput("86/\t1"):t.sendInput("8B"+(a?0:49152)+"\t"+b))}function qa(a,b,d,c,f){c||(c=M);f||(f=V);Oa[d]||(Oa[d]=!0,t.sendInput("80"+a/c+"\t"+b/f+"\t"+d))}
function ya(a){var b=a.target;v(b);if(!K)return!1;h&&h.setIMEStatus(!1);a.ctrlKey||a.shiftKey||a.metaKey||a.altKey||da.sendMissKey();b=b.getBoundingClientRect();qa(a.pageX-b.left,a.pageY-b.top,a.button);return cancelDefault(a)}function qb(a,b,d,c){d||(d=M);c||(c=V);gb=a;hb=b;t.sendInput("82"+a/d+"\t"+b/c)}function za(a){if(!K)return!1;var b=a.target;g&&"-30px"!=g.style.left&&(g.style.left="-30px");b=b.getBoundingClientRect();qb(a.pageX-b.left,a.pageY-b.top);return cancelDefault(a)}function fa(a,b,
d,c,f){c||(c=M);f||(f=V);Oa[d]=!1;t.sendInput("81"+a/c+"\t"+b/f+"\t"+d);0==d&&rb&&hi5.browser.isChrome&&u.waitForCopyContent();rb=2==d}function Aa(a){if(!K)return!1;var b=a.target.getBoundingClientRect();fa(a.pageX-b.left,a.pageY-b.top,a.button);return cancelDefault(a)}function sb(a,b,d,c,f){c||(c=M);f||(f=V);t.sendInput("83"+a/c+"\t"+b/f+"\t"+d)}function tb(a,b,d){if(!K)return!1;sb(b,d,0>a?1:0);return!1}function mb(a){(a=Fb[a])||(a=-1);return a}function ub(a){return a.none?"none":a.url?"url("+a.url+
"), pointer":0==a.data.indexOf("data:image/")?"url("+a.data+") "+a.hotX+" "+a.hotY+", default":a.data}e||(e=hi5.$("remotectrl"));if(window.svSurface&&svSurface.canvas==e&&svSurface.railWin)return svSurface.railWin.mainWin=null,window.svSurface;var C=hi5.browser.isTouch,Pa=!1,t=null,ea=!1,M=1,V=1;e.style.outline="none";var O=0,L=0,Q=e.getContext("2d"),I=null,E=null,vb=!1,aa=!1,ba=!1,ka=!1,$a=!1,sa=!0,J=null,S=!0,pa=!1,nb=!1;this.context=Q;this.fileProgress=null;var k=this,K=!0,Y=!1,T=!1,va=!1,ra=null,
U=null,g=null,Ca=null,oa=null,N=null,ca=0,ta=-1,ga=-1,ib=0,jb=0,Ma=!1,Da=null,wb=document.queryCommandSupported("copy"),gb=0,hb=0;this._cr=[82,69,77,79,84,69,83,80,65,82,75];window.svSurface=this;var w=hi5.appcfg||{img:{},toolbar:{fadable:!0}};this.setConfig=function(a){w=a};this.railWin=this.toolbar=null;this.focused=!1;this.showToolbar=!0;this.canvas=e;this.alwaysPaste=!1;"visible"in w.toolbar&&(this.showToolbar=w.toolbar.visible);var Qa=[],kb=!1,Na=!1;this.getWindow=function(){return window};this.getScale=
function(){return M};var Z=null,X=null,wa="",ia=!hi5.browser.isChromeApp&&!w.copyDialog,W=hi5.browser.isIE;this.getThumbnail=function(a){a=a||64;Z||(Z=document.createElement("canvas"));var b=Math.floor(e.height/e.width*a);Z.width!=a&&(Z.width=a);Z.height!=b&&(Z.height=b);Z.getContext("2d").drawImage(e,0,0,e.width,e.height,0,0,a,b);return Z.toDataURL()};this.initChat=function(a){var b=document.getElementById("chatWindow");hi5.Dragable(b);return new hi5.Chat(b,a)};this.equals=function(a){return e==
a.canvas};this.getFreeSpace=function(){var a=hi5.tool.getPos(e);return{width:window.innerWidth-a.x,height:window.innerHeight-a.y}};var ha=new function(){var a=1033,b=hi5.browser.isFirefox,d=hi5.browser.isMacOS||hi5.browser.isiOS,c=[0],f=null;c[8]=14;c[9]=15;c[13]=28;c[16]=42;c[17]=29;c[18]=56;c[19]=197;c[20]=58;c[27]=1;c[33]=201;c[34]=209;c[35]=207;c[36]=199;c[37]=203;c[38]=200;c[39]=205;c[40]=208;c[44]=55;c[45]=210;c[46]=211;c[48]=11;c[49]=2;c[50]=3;c[51]=4;c[52]=5;c[53]=6;c[54]=7;c[55]=8;c[56]=
9;c[57]=10;c[65]=30;c[66]=48;c[67]=46;c[68]=32;c[69]=18;c[70]=33;c[71]=34;c[72]=35;c[73]=23;c[74]=36;c[75]=37;c[76]=38;c[77]=50;c[78]=49;c[79]=24;c[80]=25;c[81]=16;c[82]=19;c[83]=31;c[84]=20;c[85]=22;c[86]=47;c[87]=17;c[88]=45;c[89]=21;c[90]=44;c[91]=219;c[92]=220;c[93]=221;c[96]=82;c[97]=79;c[98]=80;c[99]=81;c[100]=75;c[101]=76;c[102]=77;c[103]=71;c[104]=72;c[105]=73;c[106]=55;c[107]=78;c[109]=74;c[110]=83;c[111]=181;c[112]=59;c[113]=60;c[114]=61;c[115]=62;c[116]=63;c[117]=64;c[118]=65;c[119]=66;
c[120]=67;c[121]=68;c[122]=87;c[123]=88;c[144]=69;c[145]=70;c[154]=183;c[166]=59;c[167]=60;c[168]=61;c[173]=66;c[174]=67;c[175]=68;c[182]=63;c[183]=62;c[216]=64;c[217]=65;c[186]=39;c[187]=13;c[188]=51;c[189]=12;c[190]=52;c[191]=53;c[192]=41;c[219]=26;c[220]=43;c[221]=27;c[222]=40;c[224]=29;c[225]=184;var n=function(a){a=a.keyCode;if(b)switch(a){case 173:return 189;case 61:return 187;case 59:return 186;case 224:return 17}return a},p=d?function(a){switch(a){case 91:case 93:return 17;case 17:return 91;
case 229:return 69}return 0}:null;this.setLayout=function(b){a=b;var d=null,n="K"+b;n in e&&(d=e[n]());null===d&&(1033==b||0>b||3758096384<b)&&(d=c);f=d;null!==f&&console.log("Keyboard layout: "+a)};this.getKeyCode=function(a){var b=0;p&&(b=p(a.keyCode));b||(b=n?n(a):a.keyCode);return b};this.getScancode=function(a){a=ha.getKeyCode(a);return f?f[a]:0};var e=new function(){this.K3758162961=function(){var a=c.slice(0);a[244]=41;a[243]=41;a[189]=12;a[222]=13;a[220]=125;a[192]=26;a[219]=27;a[187]=39;
a[186]=40;a[221]=43;a[188]=51;a[190]=52;a[191]=53;a[226]=115;a[29]=123;a[28]=121;a[240]=112;a[242]=112;b&&(a[173]=12,a[160]=13,a[64]=26,a[59]=39,a[58]=40,n=function(a){return 220==a.keyCode&&"_"==a.key?226:a.keyCode});return a};this.K1034=this.K66570=this.K2058=this.K1040=this.K66576=function(){var a=c.slice(0);a[220]=41;a[219]=12;a[221]=13;a[186]=26;a[187]=27;a[191]=43;a[192]=39;a[189]=53;a[226]=86;b&&(a[171]=27,a[173]=53,n=function(a){var b=a.keyCode,c=a.key;if(0===b){if("\u00ba"==c||"\u00aa"==
c&&a.shiftKey||"\\"==c&&a.ctrlKey&&a.altKey)return 220;if("\u00a1"==c||"\u00bf"==c&&a.shiftKey)return 221;if("\u00e7"==c||"\u00c7"==c&&a.shiftKey||"}"==c&&a.ctrlKey&&a.altKey)return 191;if("\u00f1"==c||"\u00d1"==c&&a.shiftKey)return 192;if("DeadAcute"==c||"\u00b4\u00b4"==c||"\u00b4"==c||"DeadUmlaut"==c&&a.shiftKey||"{"==c&&a.ctrlKey&&a.altKey)return 222}else{if(192==b)return 186;if(222==b)return 219}return b});return a};this.K2057=function(){var a=c.slice(0);a[223]=41;a[222]=43;a[192]=40;a[220]=86;
b&&(a[192]=41,a[173]=12,a[61]=13,a[59]=39,a[222]=40,a[163]=43);return a};this.K1031=this.K4106=this.K5130=this.K6154=this.K7178=this.K8202=this.K9226=this.K10250=this.K11274=this.K12298=this.K13322=this.K14346=this.K15370=this.K16395=this.K17418=this.K18442=this.K19466=this.K20490=this.K99997=this.K66567=this.K2952791047=function(){var a=c.slice(0);a[220]=41;a[219]=12;a[221]=13;a[186]=26;a[187]=27;a[191]=43;a[192]=39;a[189]=53;a[226]=86;a[90]=21;a[89]=44;b&&(n=function(a){var b=a.keyCode,c=a.key;
switch(b){case 60:return 226;case 160:return 220;case 63:return 219;case 192:return 221;case 171:return 187;case 163:return 191;case 173:return 189;case 0:if("\u00f6"==c||"\u00d6"==c&&a.shiftKey)return 192;if("\u00e4"==c||"\u00c4"==c&&a.shiftKey)return 222;if("\u00fc"==c||"\u00dc"==c&&a.shiftKey)return 186}return b});return a};this.K2060=this.K99998=function(){var a=c.slice(0);a[222]=41;a[219]=12;a[189]=13;a[221]=26;a[186]=27;a[77]=39;a[192]=40;a[188]=50;a[190]=51;a[191]=52;a[187]=53;a[226]=86;a[65]=
16;a[90]=17;a[81]=30;a[87]=44;b&&(n=function(a){var b=a.keyCode,c=a.key;switch(b){case 60:return 226;case 169:return 219;case 173:return 189;case 160:return 221;case 164:return 186;case 165:return 192;case 59:return 190;case 58:return 191;case 61:return 187;case 0:if("\u00b2"==c||"\u00b3"==c&&a.shiftKey)return 222;if("\u00b5"==c||"`\u00b5"==c||"DeadGrave"==c||"\u00a3"==c&&a.shiftKey||("`"==c||"``"==c)&&a.ctrlKey&&a.altKey)return 220}return b});return a};this.K3084=this.K4105=function(){var a=c.slice(0);
a[222]=41;a[192]=40;a[226]=86;b&&(n=function(a){var b=a.keyCode,c=a.key;switch(b){case 0:if("\u00b0"==c||"\u00ac"==c&&a.ctrlKey&&a.altKey)return 222;if("\u00e7"==c||"\u00c7"==c&&a.shiftKey)return 221;if("\u00e0"==c||"DeadGrave"==c||"\u00c0"==c&&a.shiftKey)return 220;if("\u00e8"==c||"\u00c8"==c&&a.shiftKey)return 192;if("\u00e9"==c||"\u00c9"==c&&a.shiftKey)return 191;if("\u00f9"==c||"\u00d9"==c&&a.shiftKey)return 226;if("DeadTilde"==c)return 221;break;case 173:return 189;case 61:return 187;case 160:return 219;
case 59:return 186}return b});return a};this.K1036=function(){var a=c.slice(0);a[222]=41;a[219]=12;a[187]=13;a[221]=26;a[186]=27;a[220]=43;a[77]=39;a[192]=40;a[190]=51;a[191]=52;a[223]=53;a[226]=86;a[65]=16;a[90]=17;a[81]=30;a[87]=44;a[188]=50;b&&(n=function(a){var b=a.keyCode,c=a.key;switch(b){case 0:if("\u00b2"==c)return 222;if("\u00e7"==c||"\u00c7"==c&&a.shiftKey)return 221;if("\u00e0"==c||"\u00c0"==c&&a.shiftKey)return 220;if("\u00e8"==c||"\u00c8"==c&&a.shiftKey)return 192;if("\u00e9"==c||"\u00c9"==
c&&a.shiftKey)return 189;if("\u00f9"==c||"\u00d9"==c&&a.shiftKey)return 226;if("DeadTilde"==c)return 221;break;case 60:return 226;case 169:return 219;case 61:return 187;case 160:return 221;case 164:return 186;case 170:return 220;case 165:return 192;case 59:return 190;case 58:return 191;case 161:return 223}return b});return a};this.K4108=this.K2055=function(){var a=c.slice(0);a[191]=41;a[219]=12;a[221]=13;a[186]=26;a[192]=27;a[223]=43;a[222]=39;a[220]=40;a[188]=51;a[190]=52;a[189]=53;a[226]=86;a[90]=
21;a[89]=44;b&&(n=function(a){var c=a.keyCode,b=a.key;switch(c){case 0:if("\u00a7"==b||"\u00b0"==b&&a.shiftKey)return 191;if("\u00e0"==b||"\u00e4"==b&&a.shiftKey||"{"==b&&a.ctrlKey&&a.altKey)return 220;if("\u00e8"==b||"\u00fc"==b&&a.shiftKey||"["==b&&a.ctrlKey&&a.altKey)return 186;if("\u00e9"==b||"\u00f6"==b&&a.shiftKey)return 222;break;case 222:return 219;case 160:return 221;case 161:return 192;case 164:return 223;case 173:return 189;case 60:return 226}return c});return a};this.K1044=this.K1083=
function(){var a=c.slice(0);a[220]=41;a[187]=12;a[219]=13;a[221]=26;a[186]=27;a[191]=43;a[192]=39;a[222]=40;a[189]=53;a[226]=86;b&&(n=function(a){var b=a.keyCode,c=a.key;switch(b){case 0:if("\u00e5"==c||"\u00c5"==c&&a.shiftKey)return 221;if("\u00f8"==c||"\u00d8"==c&&a.shiftKey||"\u00f6"==c&&a.ctrlKey&&a.altKey)return 192;if("\u00e6"==c||"\u00c6"==c&&a.shiftKey||"\u00e4"==c&&a.ctrlKey&&a.altKey)return 222;break;case 172:return 220;case 171:return 187;case 220:return 219;case 160:return 186;case 222:return 191;
case 173:return 189;case 60:return 226}return b});return a};this.K1053=function(){var a=c.slice(0);a[220]=41;a[187]=12;a[219]=13;a[221]=26;a[186]=27;a[191]=43;a[192]=39;a[222]=40;a[189]=53;a[226]=86;b&&(n=function(a){var b=a.keyCode,c=a.key;switch(b){case 0:if("\u00a7"==c||"\u00bd"==c&&a.shiftKey)return 220;if("\u00e5"==c||"\u00c5"==c&&a.shiftKey)return 221;if("\u00f8"==c||"\u00d8"==c&&a.shiftKey||"\u00f6"==c&&a.ctrlKey&&a.altKey)return 192;if("\u00e4"==c||"\u00c4"==c&&a.shiftKey)return 222;break;
case 171:return 187;case 192:return 219;case 160:return 186;case 222:return 191;case 173:return 189;case 60:return 226}return b});return a}}},u=new function(){function a(a,c){var b=d.parseClipData(c),e=!1;"text/plain"==b.type&&(e=window.clipboardData?window.clipboardData.setData("Text",b.value)||!0:a.clipboardData.setData("text/plain",b.value)||!0,a.preventDefault());e||(hi5.browser.isIE?(e=Ea("div"),e.innerHTML=b.value,hi5.browser.selectEditable(e)):(h.resetCSS(),h.setValue(b.value),h.select()));
return b}function b(){u.copyContent&&(u.copyToClipboard("text/plain"==u.copyContent.type?"textarea":"div",u.copyContent.value),u.copyContent=null);u.waitingCopyContent=!1}var d=this;this.clipData=null;this.paste=function(a,c,b){var d=new q,e=0,e=window.clipboardData||c.clipboardData;b=null;var g=e.getData(window.clipboardData?"Text":"text/plain");if(g)d.setData("text/plain",g);else if(e)if(g=e.items)for(e=0,len=g.length;e<len;e++){if("image/png"==g[e].type){b=g[e].getAsFile();break}}else if(e.files)for(g=
e.files,e=0,len=g.length;e<len;e++)if(-1!=g[e].type.indexOf("image/png")){b=g[e];break}if(b)e=new FileReader,c.preventDefault(),e.onloadend=function(c){c.target.readyState==FileReader.DONE&&(c=hi5.Base64.enc(new Uint8Array(c.target.result)),d.setData("image/png",c),a(d))},e.readAsArrayBuffer(b);else{var k=c.target.innerHTML;I&&(I.disableTextInput=!0);E&&(E.disableTextInput=!0);var h=c.target.style.opacity;c.target.style.opacity=0;setTimeout(function(){var b=c.target.innerHTML;if(b&&b!=k){var e=c.target.childNodes;
-1<b.search(/<.*(font|color|img|table|style|class).*>/gmi)?1==e.length&&"IMG"==e[0].nodeName&&0===e[0].src.indexOf("data:image/png;base64,")?d.setData("image/png",e[0].src.substring(22)):d.setData("text/html",b):0===d.types.length&&d.setData("text/plain",b);c.target.innerHTML="";I&&I.init()}a(d);c.target.style.opacity=h;I&&(I.disableTextInput=!1);E&&(E.disableTextInput=!1)},300)}};var c=0;this.onCopy=function(b){K&&S||cancelDefault(b);if(!pa){l(!0,29);var e="copy"==b.type?"67":88;R(!0,e);R(!1,e);
l(!1,29)}if(vb){var e=(new Date).getTime(),p=e-c;c=e;if(500<p)return}if(!hi5.browser.isChromeApp){wa=t.getClipData();if(h){var g=a(b,wa);setTimeout(function(){var a=document.getElementById("_tmpEditable");a?a.parentNode.removeChild(a):(h.setValue(""),E&&E.setValue(""),"text/html"==g.type&&h.restoreCSS());0<wa.indexOf("data-sv-img")&&Ra.open(g.value,__svi18n.info.copy)},555)}d.clipData=null;sa=!1}};this.onPaste=function(a){if(!K||!S)return cancelDefault(a);if(!k.alwaysPaste&&!sa)return setTimeout(ob,
500),cancelDefault(a);sa=!1;d.paste(Eb,a,null);return!0};this.parseClipData=function(a){var b=0===a.indexOf("text/plain;"),c=0===a.indexOf("text/html;"),d=c?"text/html":"text/plain",b=b?11:c?10:0;0<b&&(a=a.substring(b));return{type:d,value:a}};this.getContent=function(){var a=Ea("div");a.focus();try{document.execCommand("paste");var b=a.innerHTML,c=new q;c.setData("text/html",b);c.setData("text/plain",a.innerText||b.replace(/<br>/gi,"\n").replace(/&nbsp;/gi," ").replace(/&amp;/gi,"&").replace(/&quot;/gi,
'"').replace(/&lt;/gi,"<").replace(/&gt;/gi,">"));c.equals(u.clipData)||(u.clipData=c,t.send("880text/plain,text/html\t0"))}finally{a.parentNode.removeChild(a),h&&(h.getElement().removeEventListener("click",u.getContent),h.focus())}};this.startPasteCmd=function(){h&&document.queryCommandSupported("paste")&&h.getElement().addEventListener("click",u.getContent)};this.waitingCopyContent=!1;this.copyContent=null;this.waitForCopyContent=function(){u.waitingCopyContent=!0;setTimeout(b,999)};this.copyToClipboard=
function(a,b){var c=Ea(a),d=!1;"div"==a?(c.innerHTML=b,hi5.browser.selectEditable(c)):(c.value=b,c.select());try{d=document.execCommand("copy",!1,null)}catch(e){}finally{c.parentNode.removeChild(c),h&&h.focus()}return d}},pb=hi5.browser.isMacOS||hi5.browser.isiOS,da=new function(){this.altUp=this.shiftUp=this.winUp=this.ctrlUp=!0;this.preKeyCode=0;var a=this;this.sendMissKey=function(){a.shiftUp||(l(!1,42),a.shiftUp=!0);a.altUp||(l(!1,56),l(!0,56),l(!1,56),a.altUp=!0);a.ctrlUp||(l(!1,29),a.ctrlUp=
!0);a.winUp||(l(!1,219),a.winUp=!0)};this.check=function(b){var d=ha.getKeyCode(b),c="keydown"==b.type;switch(d){case 16:!c||!a.shiftUp||b.altKey||b.ctrlKey||b.metaKey||a.sendMissKey();a.shiftUp=!c;break;case 17:c&&a.ctrlUp&&!b.altKey&&!b.shiftKey&&a.sendMissKey();a.ctrlUp=!c;break;case 18:!c||!a.altUp||b.shiftKey||b.ctrlKey||b.metaKey||a.sendMissKey();a.altUp=!c;break;case 91:case 92:!c||!a.winUp||b.shiftKey||b.ctrlKey||b.metaKey||b.altKey||a.sendMissKey();a.winUp=!c;break;default:!c||b.ctrlKey||
b.altKey||b.shiftKey||b.metaKey||a.sendMissKey()}}};this.requestCredential=function(a){Pa=!1;var b=__svi18n.template.login;if(b){var d=document.createElement("div");d.className="appdlg";d.innerHTML=b;document.body.appendChild(d);(b=hi5.$("loginDomain"))&&a.nbDomain&&(b.innerHTML=a.nbDomain);var c=new hi5.Lightbox(d,.9);c.onclose=function(){document.body.removeChild(d)};try{k.close()}catch(f){}c.show();(b=hi5.$("loginUser"))&&b.focus();if(b=hi5.$("frmLogin"))b.onsubmit=function(){var a=hi5.$("loginUser").value,
b=hi5.$("loginPassword").value,d=hi5.$("loginDomain").innerHTML;c.dismiss();setTimeout(function(){t.reconnect(a,b,d)},5);return!1}}else k.showMessage("No value for login template")};var h=null;if(C)ab();else{var Sa=hi5.$("tmContainer");Sa&&Sa.parentNode.removeChild(Sa)}h=new Va;C&&hi5.browser.isSafari&&window.addEventListener("scroll",function(){setTimeout(function(){var a=hi5.$("pc_key");a&&(a.style.top=window.pageYOffset+"px");k.toolbar&&(k.toolbar.style.top=window.pageYOffset+"px")},200)},!1);
this.setCaretPos=function(a,b){};this.showMessage=function(a,b){a&&w.displayMsg&&hi5.notifications.notify({msg:a,timeout:b||0})};this.hideWhenClose="hideWhenClose"in w?w.hideWhenClose:!0;this.setReadOnly=function(a){K=!a};this.setPlayerMode=function(){T=!0;k.showToolbar=!1;k.setReadOnly(!0);k.hideWhenClose=!1};this.setAutoScale=function(a){"autoScale"in w&&(a=w.autoScale);a?(la(!0),Wa("hidden")):la(!1);ea=a};this.setTouchpad=function(a){Y=a;var b=hi5.$("touchpadMode");b&&(b.checked=a,b.onchange=function(a){Y=
a.target.checked});a?g||Ba():g&&g.parentNode&&(g.parentNode.removeChild(g),g=null)};this.setExtKeyboard=function(a){if(C){h.adjust(!0);h.setContentEditable(a?"true":"false");ca=a?1:0;hi5.browser.isChrome&&h.setFontSize("2em");a&&h.focus();var b=hi5.$("extKBD");b&&b.checked!=a&&(b.checked=a)}};this.focus=function(){h&&v(h.getElement())};this.getInputElement=function(){return h};this.scaleTo=function(a,b,d){a/=O;b/=L;d?(M=a,V=b):V=M=b=a=Math.min(a,b);hi5.tool.scale(e.parentNode,a,b)};this.setSize=function(a,
b,d){O=a;L=b;ea||Wa(d);e.width=O;e.height=L;ea&&la(!0);C&&ab();h||(h=new Va);h.adjust();U&&U.visible()&&U.dismiss()};this.reposition=function(){h.adjust()};this.setController=function(a){t=a;t.sendInput||(t.sendInput=t.send);C&&hi5.browser.setOrientaionHandler(function(){ea?la(!0):setTimeout(function(){t.onorientationchange({svSurface:k,innerWidth:window.innerWidth,innerHeight:window.innerHeight});w.disableScoll||window.scrollTo(0,0)},300)})};this.setFileHandler=function(a){"FileReader"in window||
(a=null);if(a){if(!J&&!T&&hi5.$("filecontainer")){J=a;k.fileProgress=new hi5.ProgressBar(hi5.$("total"));Ja();Cb();var b=document.getElementById("__cancelUpload");b&&b.addEventListener("click",function(){J.cancelAll()},!1);J.addEvent("beforeupload",function(a,c){b&&(b.style.visibility="visible");k.fileProgress.style.display="block";k.fileProgress.maxValue+=a.size});J.addEvent("uploaded",function(){b&&(b.style.visibility="hidden");k.fileProgress.maxValue=0;k.fileProgress.style.display="none";k.showMessage(__svi18n.file.uploadDone,
5E3);k.refreshFiles()});J.addEvent("progress",function(a){k.fileProgress.setProgress(a)})}}else J=null,k.fileProgress=null,k.toolbar&&k.toolbar.removeButton("svCloud"),Ja()};this.setFeature=function(a){var b;!T&&a&16?a&128&&(b=hi5.$("uploadfile"))&&(b.style.visibility="hidden"):k.setFileHandler(null);a&256||(b=hi5.$("shadowing"))&&b.parentNode.removeChild(b);a&1024||(b=hi5.$("ssParent"))&&b.parentNode.removeChild(b)};var Fa=new function(){function a(){if(0===d.length){c=!1;var a=hi5.$("_sv_pdf_parent");
a&&a.visible&&a.visible()&&a.dismiss&&a.dismiss();a&&a.parentNode&&(a.parentNode.removeChild(a),console.log("pdf removed"))}else b()}function b(){var b=d.shift();if(b){var e=hi5.$("_sv_pdf_parent"),g=__svi18n.info.printready||"Your document is ready.",g=C||w.showPDFLink?'<p style="text-align:center;line-height:4em"><a href="'+b+'" target="_blank">'+g+"</a></p>":(hi5.browser.isChromeApp?"<webview":"<iframe")+' src="'+b+'" width="100%" height="100%" id="_iFramePDF">'+(hi5.browser.isChromeApp?"</webview>":
"</iframe>");if(e){var k=hi5.$("_iFramePDF");k?k.src=b:e.innerHTML+=g}else e=document.createElement("div"),e.style.backgroundColor="white",e.style.width=C?"30%":"90%",e.style.height=C?"4elm":"85%",e.id="_sv_pdf_parent",e.innerHTML=g,document.body.appendChild(e),b=new hi5.Lightbox(e),b.onclose=a,b.show()}c=!0}var d=[],c=!1;this.clearPDF=function(){a()};this.showPDF=function(a){d.push(a);c||b()}};this.close=function(){Ga();Fa.clearPDF();ea&&k.setAutoScale(!1);X&&X.setVisibility(!1);for(var a=0,b=Qa.length;a<
b;a++)Qa[a]();try{J=null;k.fileProgress=null;window.svSurface=null;g&&g.parentNode&&(g.parentNode.removeChild(g),g=null);$a=!0;if(!window||T)return;if(0<hi5.notifications.notifySize()){hi5.notifications.onempty=function(){k.close();hi5.notifications.onempty=null};return}if(Pa)window.close();else if(this.hide(),hi5.browser.isChromeApp){var d=chrome.app.window.current();d&&(d.onMaximized.removeListener(Xa),d.isFullscreen()&&(d.restore(),d.restore()))}}catch(c){}"clearScreen"in w&&!w.clearScreen||Q.fillRect(0,
0,e.width,e.height)};this.setFastCopy=function(a){vb=a};this.drawLicense=function(a){if(0!=w.drawLicense){var b=a.charAt(0);Q.font="12pt Arial";Q.fillStyle="W"==b?"red":"black";a=a.substring(1);Q.fillText(a,10,L-24)}};this.drawText=function(a){var b=w.text||{};if(b.backgroundFillStyle){var d=e.width,c=e.height;Q.fillStyle=b.backgroundFillStyle;Q.fillRect(0,0,d,c)}var f=20,g=50;"center"==b.textAlign&&(f=d/2,g=c/2);Q.font=b.font||"18pt Arial";Q.fillStyle=b.fillStyle||"black";b.textAlign&&(Q.textAlign=
b.textAlign);b.textBaseline&&(Q.textBaseline=b.textBaseline);Q.fillText(a,f,g)};this.showPDF=function(a){Fa.showPDF(a)};this.hide=function(){k.hideWhenClose&&(e.height=1,e.width=1);h&&h.hide()};var xa=0,xb=!1,Ra=new function(){var a=null,b=null;this.createDialog=function(d,c,f){var e=document.createElement("div");e.className="copyDialog";var g=document.createElement("div");g.innerHTML=c;g.className="hi5_notifer_title";e.appendChild(g);c=document.createElement(f);"div"==f?c.innerHTML=d:c.value=d;c.style.border=
"1px solid #666";c.style.width="100%";c.style.minHeight="80px";e.appendChild(c);a=c;wb&&(b=document.createElement("input"),b.className="btnCopy",b.type="button",b.value=__svi18n.info.copylable||"Copy",b.onclick=function(){"div"==f?hi5.browser.selectEditable(a):a.select();document.execCommand("copy")},e.appendChild(b));if(0<d.indexOf('data-sv-img="wmf"')&&(c=d.indexOf('src="')+5,g=d.indexOf('"',c),g>c&&0<c)){var k=document.createElement("a");k.href=d.substring(c,g);k.target="_blank";k.innerHTML="Download image";
e.appendChild(k)}return e};this.open=function(d,c,e){function g(){var h=Ra.createDialog(d,c,e);document.body.appendChild(h);var l=new hi5.Lightbox(h);l.show();a&&0!==d.indexOf("<img ")&&("div"==e?hi5.browser.selectEditable(a):a.select());Ia();l.onclose=function(){Ha();h&&h.parantNode&&h.parantNode.removeChild(h);k.toolbar&&k.toolbar.removeButton("_svClipInfo")};document.queryCommandEnabled("copy")||h.removeChild(b)}e||(e="div");if(w.clipWarnAlways||!xb)k.showMessage(__svi18n.info.copyWarning,5E3),
xb=!0;clearTimeout(xa);var h=k.toolbar;if(h){var l=h.getButton("_svClipInfo");l?l.onclick=g:(l=h.addButton(w.img.copy?w.img.copy:"copy.png",g),l.id="_svClipInfo",l.className="pulse");h.startFade();xa=setTimeout(function(){k.toolbar.removeButton("_svClipInfo")},3E4)}}};this.copyToClip=function(a,b){var d=u.parseClipData(a);u.waitingCopyContent?u.copyContent=d:setTimeout(function(){if(!(!S||ia&&wa==a||N)){a=d.value;var b=0<a.indexOf("<img ")||w.copyDialog,e="text/plain"==d.type?"textarea":"div";if(!b||
wb)b=!u.copyToClipboard(e,a);b&&Ra.open(a,__svi18n.info.copy,e)}},50)};this.fullScreen=function(){e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT)};Qa.push(function(){if(window){window.removeEventListener("beforeunload",Za,!1);window.removeEventListener("focus",Ya,!1);window.onresize=null;try{ra&&ra.parentNode&&(ra.parentNode.removeChild(ra),ra=null),h&&h.remove(),h=null}catch(a){}}if(document){Ia();document.body.style.overflow="";var b=window;try{for(;;){b.document.removeEventListener("mouseup",
fb,!1);if(b.parent==b)break;b=b.parent}}catch(d){}}});var X=new function(){function a(a){ca=(new Date).getTime();if(a=hi5.$("pc_key"))a.style.display="block",a.style.top=window.pageYOffset+"px",E&&(E.setValue("`\t`"),E.select())}function b(a){ca=0;if(a=hi5.$("pc_key"))a=hi5.$("shortcuts"),a&&a.checked||(m.style.display="none")}function d(){e&&(aa?hi5.html.addClass(e,"button_selected"):hi5.html.removeClass(e,"button_selected"));g&&(ba?hi5.html.addClass(g,"button_selected"):hi5.html.removeClass(g,"button_selected"));
h&&(ka?hi5.html.addClass(h,"button_selected"):hi5.html.removeClass(h,"button_selected"))}function c(a){cancelDefault(a);a=a.target;var b=a.innerHTML,b=b.replace(/\u2190/g,"left").replace(/\u2191/g,"up").replace(/\u2192/g,"right").replace(/\u2193/g,"down");switch(b){case "Ctrl":e||(e=a);aa?l(!1,29):l(!0,29);aa=!aa;d();break;case "Alt":g||(g=a);ba?l(!1,56):l(!0,56);ba=!ba;d();break;case "Shift":h||(h=a);ka?l(!1,42):l(!0,42);ka=!ka;d();break;case "...":if(a=hi5.$("pc_key_more"))a.style.display="block"==
a.style.display?"none":"block";break;case "Start":b="Ctrl+Esc";default:k.writeKeyComb(b),r.resetModifier()}}var e=null,g=null,h=null,r=this;this.setVisibility=function(c){c?a():b()};this.resetModifier=function(){ba&&(ba=!1,l(!1,56));aa&&(aa=!1,l(!1,29));ka&&(ka=!1,l(!1,42));d()};hi5.$("svTouchInput")&&(hi5.$("svTouchInput").addEventListener("focus",a,!1),hi5.$("svTouchInput").addEventListener("blur",b,!1));var m=hi5.$("pc_key");if(m){var q=m.getElementsByTagName("span"),t=q.length,u=hi5.browser.isFirefox?
"mousedown":"touchstart";"ontouchstart"in window||(navigator.pointerEnabled?u="pointerdown":navigator.msPointerEnabled&&(u="MSPointerDown"));for(var x=0;x<t;x++){var v=q[x];v.className="button";v.addEventListener(u,c,!1);"mousedown"!=u&&v.addEventListener("mousedown",c,!1)}m.style.position="absolute"}},yb=hi5.$("shortcuts");yb&&yb.addEventListener("change",function(a){X.setVisibility(a.target.checked)});this.setKeysVisibility=function(a){X&&X.setVisibility(a)};this.refreshFiles=function(){U&&U.visible()?
ma(".",U):db(null)};this.processLink=function(a){function b(b){window.open(a);b.target.parentNode.removeChild(b.target)}clearTimeout(xa);var d=k.toolbar,c=d.getButton("_svLinkInfo");c?c.onclick=b:(c=d.addButton(w.img.link?w.img.link:"link.png",b),c.id="_svLinkInfo",c.className="pulse");c.title=a;d.startFade();xa=setTimeout(function(){k.toolbar.removeButton("_svLinkInfo")},1E4)};this.setUnicode=function(a){h&&(!a&&C&&(hi5.browser.isiOS||hi5.browser.isChrome&&!hi5.browser.isWindows)&&(a=!0),va=!a,svGlobal.logger.warn("Unicode:"+
a),I.onkeydown=I.onkeyup=a?bb:Db,I.ontextinput=cb)};this.setTouchRemoting=function(a){!0===a?(oa=new y(k,e),svGlobal.logger.info("touch remoting"),k.showMessage(__svi18n.info.touchremoting)):oa=new H(k)};this.setClipboard=function(a){(S=a)||(ia=!1)};this.setJoinMode=function(a){t.setJoinMode(a)};this.requestControl=function(){t.requestControl()};this.run=function(a){hi5.notifications.clearAll();3758162961!=a&&3758162962!=a||!h||h.setContentEditable("false");ha.setLayout(a);var b=-1!=[99997,99998,
99999].indexOf(a);va=!b;kb=(b||-1==[1033,3758162961,3758162962,1049].indexOf(a))&&hi5.browser.isMacOS;Pa="boolean"==typeof w.closeOnDisconn?w.closeOnDisconn:!!window.opener&&!hi5.browser.isChromeApp;w.disableScoll||window.scrollTo(0,0);Ja();Ab();a=h.getElement();if(C){if(!T){oa=new H(k);var d=new x(a);d.ontouch=P;d.onmousedown=ya;d.onmousemove=za;d.onmouseup=Aa;D(a,tb,!1);document.addEventListener("paste",u.onPaste,!1);S&&ia&&(document.addEventListener("copy",u.onCopy,!1),document.addEventListener("cut",
u.onCopy,!1))}}else T||(a.addEventListener("mousemove",za,!1),a.addEventListener("mousedown",ya,!1),a.addEventListener("mouseup",Aa,!1),D(a,tb,!1),a.addEventListener("paste",u.onPaste,!1),S&&ia&&(a.addEventListener("copy",u.onCopy,!1),a.addEventListener("cut",u.onCopy,!1))),v(a);h.adjust();k.setUnicode(b);b=window;try{for(;;){b.document.addEventListener("mouseup",fb,!1);if(b.parent==b)break;b=b.parent}}catch(c){}this.drawText(__svi18n.wait);if(k.onstart)k.onstart(e);S&&u&&u.startPasteCmd()};this.movCursorBy=
Ka;this.moveCursor=na;this.touchstart=function(a){switch(a.pointes){case 1:if(Y)g||Ba(),La("touchstart",a.screenX,a.screenY,!a.flick);else if(!a.flick||r()){var b=h.getElement().getBoundingClientRect();qa(a.x-b.left,a.y-b.top,0)}break;case 2:ta=a.screenX,ga=a.screenY}};this.touchmove=function(a){var b=h.getElement().getBoundingClientRect();switch(a.pointes){case 1:Y?La("touchmove",a.screenX,a.screenY,!a.flick):a.flick&&!r()||qb(a.x-b.left,a.y-b.top);break;case 2:40<=Math.abs(a.screenY-ga)&&(sb(a.x-
b.left,a.y-b.top,0<a.screenY-ga?0:1),ta=a.screenX,ga=a.screenY)}};this.touchend=function(a){var b=a.pointes,d=h.getElement().getBoundingClientRect();switch(b){case 1:Y?La("touchend",a.screenX,a.screenY,!a.flick):(na(a.x,a.y,!0),a.flick&&!r()||fa(a.x-d.left,a.y-d.top,0));break;case 2:a.moved||(b=Y?g.scrX:a.x-d.left,a=Y?g.scrY:a.y-d.top,na(b,a),qa(b,a,2),fa(b,a,2));break;case 3:if(a.gesture)switch(a.gesture){case "OPEN":l(!0,219);l(!0,200);l(!1,200);l(!1,219);break;case "CLOSE":l(!0,219);l(!0,208);
l(!1,208);l(!1,219);break;case "LEFT":l(!0,56);l(!0,1);l(!1,1);l(!1,56);break;case "RIGHT":l(!0,42);l(!0,56);l(!0,1);l(!1,1);l(!1,56);l(!1,42);break;case "UP":l(!0,42);l(!0,219);R(!0,77);R(!1,77);l(!1,219);l(!1,42);break;case "DOWN":l(!0,219),R(!0,77),R(!1,77),l(!1,219)}else k.toolbar&&k.toolbar.startFade&&k.toolbar.startFade(),N&&N.focus()}};this.flick=function(a){switch(a.from){case 4:t.sendInput("840\t209");t.sendInput("8449152\t209");break;case 2:t.sendInput("840\t201"),t.sendInput("8449152\t201")}};
this.longpress=function(a){Y&&(a.pointes=2);var b=h.getElement().getBoundingClientRect();switch(a.pointes){case 1:var d=a.x-b.left;a=a.y-b.top;na(d,a);qa(d,a,2);fa(d,a,2);break;case 2:g&&(qa(g.scrX,g.scrY,2,1),fa(g.scrX,g.scrY,2,1))}};this.redirectTouches=function(a){if(K){for(var b=a.length,d,c="90"+b,e=0;e<b;e++)d=a[e],c=c+"\t"+d.contactId+";"+d.contactFlags+";"+Math.floor(d.x/M)+";"+Math.floor(d.y/V);t.send(c)}};var ua=0;this.processClipReq=function(a){var b=u.clipData,d=b?b.getData(a):null;if(d)return t.send("881"+
a+"\t"+d),b.sent=!0;t.send("881"+a+"\t"+("text/plain"==a?"":"ERROR"));return!1};var Oa={},rb=!1,Fb={33:201,34:209,35:207,36:199,37:203,38:200,39:205,40:208,154:183,45:210,46:211,225:184,91:219,92:220,93:221,27:1,8:14,9:15,13:28,224:29,17:29,16:42,18:56,20:58,166:59,112:59,167:60,113:60,168:61,114:61,183:62,115:62,182:63,116:63,216:64,117:64,217:65,118:65,173:66,119:66,174:67,120:67,175:68,121:68,122:87,123:88};this.writeKeyComb=function(a){t.writeKeyComb(a)};this.setCursor=function(a){!w.disableCursor&&
a&&(a.data||a.url||a.none)&&(Ca=a,g&&g.setCursor(a),T||(h?(h.getElement().style.cursor="default",h.getElement().style.cursor=ub(a)):e.style.cursor=ub(a)))};this.setVisible=function(a,b){var d=a?"visible":"hidden";"number"==typeof b?setTimeout(function(){e.style.visibility=d},b):e.style.visibility=d}}svGlobal.LocalInterface=LocalInterface;
svGlobal.rdpFile={loadRdpFile:function(e,v){var q=v.elements,F=e.split("\r\n");2>F.length&&(F=e.split("\n"));if(2>F.length)return!1;var D=hi5.$("gateway"),x=D.value;v.reset();D.value=x;D=0;for(x=F.length;D<x;D++){var r=F[D],y=r.indexOf(":"),H=r.substring(0,y),r=r.substring(y+3),H=H.toLowerCase();switch(H){case "full address":y=r.indexOf(":");0<y?(q.server.value=r.substring(0,y),q.port.value=r.substring(y+1)):q.server.value=r;break;case "username":q.user.value=r;break;case "domain":q.domain.value=
r;break;case "connect to console":q.useConsole.checked="0"!=r;break;case "desktopwidth":q.width.value=r;break;case "desktopheight":q.height.value=r;break;case "session bpp":q.server_bpp.value=r;break;case "audiomode":q.playSound.value=r;break;case "alternate shell":0<r.length&&(q.command.value=r,hi5.$("app").checked||(hi5.$("shell").checked=!0));break;case "shell working directory":q.directory=r;break;case "redirectclipboard":q.mapClipboard.checked="0"!=r;break;case "redirectprinters":q.mapPrinter.checked=
"0"!=r;break;case "server port":0<r.length&&(q.port.value=r);break;case "disable wallpaper":q.background.checked="0"==r;break;case "disable themes":q.styles.checked="0"==r;break;case "disable menu anims":q.animation.checked="0"==r;break;case "disable full window drag":q.contents.checked="0"==r;break;case "allow font smoothing":q.smoothfont.checked="0"!=r;break;case "allow desktop composition":q.composition.checked="0"!=r;break;case "bitmapcachepersistenable":q.bitmap.checked="0"!=r;break;case "remoteapplicationprogram":q.exe.value=
r;break;case "remoteapplicationcmdline":q.args.value=r;break;case "remoteapplicationmode":hi5.$("app").checked="1"==r;break;case "loadbalanceinfo":q.loadBalanceInfo.value=r}}return!0},handleFiles:function(e,v){if(1!=e.length)hi5.notifications.notify({msg:"Please one file only"});else{var q=e[0],F=q.name,D=F.length;if(4<D&&".rdp"==F.substring(D-4).toLowerCase()){var x=new FileReader,r=!1;x.onload=function(e){!(e=e.target.result)||svGlobal.rdpFile.loadRdpFile(e,v)||r||(r=!0,x.readAsText(q))};x.readAsText(q,
"UTF-16LE")}else hi5.notifications.notify({msg:"Sorry, Please .rdp file only"})}}};
function initDragDrop(e,v){function q(e){svGlobal.rdpFile.handleFiles(e.target.files,v)}function F(q){cancelDefault(q);e.style.backgroundColor=r;svGlobal.rdpFile.handleFiles(q.dataTransfer.files,v)}function D(q){cancelDefault(q);e.style.backgroundColor="yellow"}function x(q){cancelDefault(q);e.style.backgroundColor=r}if("FileReader"in window){var r=e.style.backgroundColor,y=hi5.$("rdpfile");y&&y.addEventListener("change",q,!1);e.addEventListener("dragover",D,!1);e.addEventListener("dragleave",x,!1);
e.addEventListener("drop",F,!1)}}svGlobal.util.initDragDrop=initDragDrop;
svGlobal.util.initMapDisk=function(e,v){function q(q){cancelDefault(q);"0.6"!=e.style.opacity&&(e.style.opacity="0.6");e.style.backgroundColor="yellow"}function F(q){cancelDefault(q);e.style.opacity=e.__oldOpacity;e.style.backgroundColor=e.__oldColor}function D(q){cancelDefault(q);e.style.opacity=e.__oldOpacity;e.style.backgroundColor=e.__oldColor;var r=hi5.file.getEntries(q);r.length?(q=new hi5.file.DirectoryReader(r),q.onfile=function(e,q){v.addFile(e,q)},q.start()):v.addFiles(q.dataTransfer.files)}
"FileReader"in window&&(e.__oldColor=e.style.backgroundColor,e.__oldOpacity=e.style.opacity,e.addEventListener("dragover",q,!1),e.addEventListener("dragleave",F,!1),e.addEventListener("drop",D,!1))};window.addEventListener("load",function(e){e=document.getElementsByClassName("ver");for(var v=e.length,q=0;q<v;q++)e[q].innerHTML=svGlobal.version},!1);svGlobal.logger.info("ver:"+svGlobal.version);
